# Cloud Build pipeline for HeyAI-backend -> Cloud Run
# Prereqs:
# - Artifact Registry repo exists: $_AR_REPO in $_REGION
# - Secrets exist in Secret Manager: ELEVENLABS_API_KEY, ELEVEN_VOICE_ID
# - APIs enabled: run.googleapis.com, cloudbuild.googleapis.com, artifactregistry.googleapis.com, secretmanager.googleapis.com

substitutions:
  _SERVICE_NAME: "heyai-backend"
  _AR_REPO: "services"
  _REGION: "us-central1"
  _VERTEX_AI_LOCATION: "us-central1"
  _VERTEX_AI_MODEL: "gemini-2.5-flash"
  _KOOZIE_AGENT_URI: ""

options:
  substitution_option: ALLOW_LOOSE

images:
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/heyai-backend:$COMMIT_SHA"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-f"
      - HeyAI-backend/Dockerfile
      - "-t"
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/heyai-backend:$COMMIT_SHA"
      - HeyAI-backend

  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/heyai-backend:$COMMIT_SHA"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - "$_SERVICE_NAME"
      - "--image"
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/heyai-backend:$COMMIT_SHA"
      - "--region"
      - "$_REGION"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--set-env-vars"
      - "GCP_PROJECT_ID=$PROJECT_ID,GCP_REGION=$_REGION,VERTEX_AI_LOCATION=$_VERTEX_AI_LOCATION,VERTEX_AI_MODEL=$_VERTEX_AI_MODEL,KOOZIE_AGENT_URI=$_KOOZIE_AGENT_URI"
      - "--set-secrets"
      - "ELEVENLABS_API_KEY=ELEVENLABS_API_KEY:latest,ELEVEN_VOICE_ID=ELEVEN_VOICE_ID:latest"


